/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

LOCK TABLES `organizations` WRITE;
/*!40000 ALTER TABLE `organizations` DISABLE KEYS */;
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (0,'中国烟草总公司','总公司',0,0,0,0,1);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (1,'中国烟草总公司浙江省公司','浙江省公司',0,0,0,0,1);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (2,'浙江省烟草公司杭州市公司','杭州市公司',1,1,0,0,1);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (3,'浙江省烟草公司宁波市公司','宁波市公司',1,1,0,0,2);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (4,'浙江省烟草公司温州市公司','温州市公司',1,1,0,0,3);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (5,'浙江省烟草公司嘉兴市公司','嘉兴市公司',1,1,0,0,4);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (6,'浙江省烟草公司湖州市公司','湖州市公司',1,1,0,0,5);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (7,'浙江省烟草公司绍兴市公司','绍兴市公司',1,1,0,0,6);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (8,'浙江省烟草公司金华市公司','金华市公司',1,1,0,0,7);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (9,'浙江省烟草公司衢州市公司','衢州市公司',1,1,0,0,8);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (10,'浙江省烟草公司丽水市公司','丽水市公司',1,1,0,0,9);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (11,'浙江省烟草公司台州市公司','台州市公司',1,1,0,0,10);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (12,'浙江省烟草公司舟山市公司','舟山市公司',1,1,0,0,11);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (13,'杭州市烟草公司萧山分公司','萧山分公司',2,1,0,0,1);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (14,'杭州市烟草公司余杭分公司','余杭分公司',2,1,0,0,2);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (15,'杭州市烟草公司富阳分公司','富阳分公司',2,1,0,0,3);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (16,'杭州市烟草公司临安分公司','临安分公司',2,1,0,0,4);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (17,'杭州市烟草公司桐庐分公司','桐庐分公司',2,1,0,0,5);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (18,'杭州市烟草公司建德分公司','建德分公司',2,1,0,0,6);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (19,'杭州市烟草公司淳安分公司','淳安分公司',2,1,0,0,7);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (20,'宁波市烟草公司余姚分公司','余姚分公司',3,1,0,0,1);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (21,'宁波市烟草公司慈溪分公司','慈溪分公司',3,1,0,0,2);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (22,'宁波市烟草公司奉化分公司','奉化分公司',3,1,0,0,3);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (23,'宁波市烟草公司宁海分公司','宁海分公司',3,1,0,0,4);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (24,'宁波市烟草公司象山分公司','象山分公司',3,1,0,0,5);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (25,'宁波市烟草公司鄞州分公司','鄞州分公司',3,1,0,0,6);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (26,'宁波市烟草公司镇海分公司','镇海分公司',3,1,0,0,7);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (27,'宁波市烟草公司北仑分公司','北仑分公司',3,1,0,0,8);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (28,'温州市烟草公司乐清分公司','乐清分公司',4,1,0,0,1);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (29,'温州市烟草公司永嘉分公司','永嘉分公司',4,1,0,0,2);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (30,'温州市烟草公司文成分公司','文成分公司',4,1,0,0,3);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (31,'温州市烟草公司瑞安分公司','瑞安分公司',4,1,0,0,4);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (32,'温州市烟草公司平阳分公司','平阳分公司',4,1,0,0,5);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (33,'温州市烟草公司洞头分公司','洞头分公司',4,1,0,0,6);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (34,'温州市烟草公司苍南分公司','苍南分公司',4,1,0,0,7);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (35,'温州市烟草公司泰顺分公司','泰顺分公司',4,1,0,0,8);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (36,'嘉兴市烟草公司嘉善分公司','嘉善分公司',5,1,0,0,1);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (37,'嘉兴市烟草公司平湖分公司','平湖分公司',5,1,0,0,2);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (38,'嘉兴市烟草公司海盐分公司','海盐分公司',5,1,0,0,3);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (39,'嘉兴市烟草公司海宁分公司','海宁分公司',5,1,0,0,4);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (40,'嘉兴市烟草公司桐乡分公司','桐乡分公司',5,1,0,0,5);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (41,'湖州市烟草公司长兴分公司','长兴分公司',6,1,0,0,1);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (42,'湖州市烟草公司安吉分公司','安吉分公司',6,1,0,0,2);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (43,'湖州市烟草公司德清分公司','德清分公司',6,1,0,0,3);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (44,'绍兴市烟草公司诸暨分公司','诸暨分公司',7,1,0,0,1);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (45,'绍兴市烟草公司上虞分公司','上虞分公司',7,1,0,0,2);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (46,'绍兴市烟草公司嵊州分公司','嵊州分公司',7,1,0,0,3);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (47,'绍兴市烟草公司新昌分公司','新昌分公司',7,1,0,0,4);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (48,'金华市烟草公司义乌分公司','义乌分公司',8,1,0,0,1);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (49,'金华市烟草公司东阳分公司','东阳分公司',8,1,0,0,2);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (50,'金华市烟草公司永康分公司','永康分公司',8,1,0,0,3);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (51,'金华市烟草公司兰溪分公司','兰溪分公司',8,1,0,0,4);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (52,'金华市烟草公司浦江分公司','浦江分公司',8,1,0,0,5);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (53,'金华市烟草公司武义分公司','武义分公司',8,1,0,0,6);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (54,'金华市烟草公司磐安分公司','磐安分公司',8,1,0,0,7);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (55,'衢州市烟草公司江山分公司','江山分公司',9,1,0,0,1);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (56,'衢州市烟草公司龙游分公司','龙游分公司',9,1,0,0,2);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (57,'衢州市烟草公司常山分公司','常山分公司',9,1,0,0,3);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (58,'衢州市烟草公司开化分公司','开化分公司',9,1,0,0,4);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (59,'丽水市烟草公司青田分公司','青田分公司',10,1,0,0,1);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (60,'丽水市烟草公司缙云分公司','缙云分公司',10,1,0,0,2);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (61,'丽水市烟草公司龙泉分公司','龙泉分公司',10,1,0,0,3);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (62,'丽水市烟草公司遂昌分公司','遂昌分公司',10,1,0,0,4);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (63,'丽水市烟草公司松阳分公司','松阳分公司',10,1,0,0,5);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (64,'丽水市烟草公司庆元分公司','庆元分公司',10,1,0,0,6);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (65,'丽水市烟草公司云和分公司','云和分公司',10,1,0,0,7);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (66,'丽水市烟草公司景宁分公司','景宁分公司',10,1,0,0,8);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (67,'台州市烟草公司玉环分公司','玉环分公司',11,1,0,0,1);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (68,'台州市烟草公司温岭分公司','温岭分公司',11,1,0,0,2);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (69,'台州市烟草公司黄岩分公司','黄岩分公司',11,1,0,0,3);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (70,'台州市烟草公司临海分公司','临海分公司',11,1,0,0,4);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (71,'台州市烟草公司天台分公司','天台分公司',11,1,0,0,5);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (72,'台州市烟草公司仙居分公司','仙居分公司',11,1,0,0,6);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (73,'台州市烟草公司三门分公司','三门分公司',11,1,0,0,7);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (74,'舟山市烟草公司普陀分公司','普陀分公司',12,1,0,0,1);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (75,'舟山市烟草公司岱山分公司','岱山分公司',12,1,0,0,2);
INSERT INTO `organizations` (`id`,`name`,`alias`,`superior_id`,`sub_root_id`,`type`,`state`,`list_order`) VALUES (76,'舟山市烟草公司嵊泗分公司','嵊泗分公司',12,1,0,0,3);
/*!40000 ALTER TABLE `organizations` ENABLE KEYS */;
UNLOCK TABLES;

/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
